# Generated by Django 4.0.6 on 2022-07-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
